AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  Extract:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: singapore_weather_extract
      CodeUri: ./extract
      Handler: extract.lambda_handler
      Environment:
        Variables:
          api_key: 
          BUCKET_NAME: !Ref S3_BUCKET
      Role:
        Fn::GetAtt:
        - ExtractRole
        - Arn
      Runtime: python3.10
      Timeout: 3
      MemorySize: 256
  ExtractRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: LambdaPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:CreateLogGroup
            - logs:PutLogEvents
            Resource: '*'
