name: Deploying multiple Lambdas
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1
      - run: sam build --use-container --build-image public.ecr.aws/sam/build-python3.10:1.94.0-20230727191512 -t sam-template.yml
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name extract --s3-bucket data-pipeline-test-000001 --capabilities CAPABILITY_IAM --region ap-southeast-1 --on-failure DELETE